### ISSUE TITLE
Can't import theano

### ISSUE THREAD

**Issue by alekaizer** [pyenv/pyenv-installer#56]
After installing py 3.5.3 through pyenv, and installing theano

I run the interpreter and tried to import theano and I got this:

```
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -march=ivybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=15360 -mtune=ivybridge -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/numpy/core/include -I/root/.pyenv/versions/3.5.3/include/python3.5m -I/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/gof -L/root/.pyenv/versions/3.5.3/lib -fvisibility=hidden -o /root/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.3-64/lazylinker_ext/lazylinker_ext.so /root/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.3-64/lazylinker_ext/mod.cpp -lpython3.5m
/usr/bin/ld: /root/.pyenv/versions/3.5.3/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/root/.pyenv/versions/3.5.3/lib/libpython3.5m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 75, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/__init__.py", line 66, in <module>
    from theano.compile import (
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/compile/__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/compile/function_module.py", line 21, in <module>
    import theano.compile.mode
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/compile/mode.py", line 10, in <module>
    import theano.gof.vm
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/gof/vm.py", line 662, in <module>
    from . import lazylinker_c
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/theano/gof/cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): /usr/bin/ld: /root/.pyenv/versions/3.5.3/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC. /root/.pyenv/versions/3.5.3/lib/libpython3.5m.a: error adding symbols: Bad value. collect2: error: ld returned 1 exit status. 
```

Can someone help figuring out what the solution can be?

**Comment by joshfriend** [comment]
Try building python with `--enable-shared`: https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared

**Comment by alekaizer** [comment]
@joshfriend I did, it hasn't worked either

**Comment by alekaizer** [comment]
@joshfriend It finally works, I retried in a fresh installed machine
